behaviors:
  VisPoseEstimator:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512 # 5120
      buffer_size: 2048 # 409600 
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1e8
    time_horizon: 2048 # 64
    summary_freq: 50000
    keep_checkpoints: 5
environment_parameters:
  difficulty:
    curriculum:
      - name: Dist1
        completion_criteria:
          measure: progress
          behavior: WeldingAgent
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 0.2
        value: 1.0
      - name: Dist2
        completion_criteria:
          measure: progress
          behavior: WeldingAgent
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 0.2
        value: 2.0
      - name: Dist3
        completion_criteria:
          measure: progress
          behavior: WeldingAgent
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 0.2
        value: 3.0
      - name: Dist4
        completion_criteria:
          measure: progress
          behavior: WeldingAgent
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 0.2
        value: 4.0
      - name: Dist5
        completion_criteria:
          measure: progress
          behavior: WeldingAgent
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 0.2
        value: 5.0
      - name: Dist6
        completion_criteria:
          measure: progress
          behavior: WeldingAgent
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 0.2
        value: 6.0
      - name: Dist7
        completion_criteria:
          measure: progress
          behavior: WeldingAgent
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 0.2
        value: 7.0
      - name: Dist8
        completion_criteria:
          measure: progress
          behavior: WeldingAgent
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 0.2
        value: 8.0
      - name: Dist9
        completion_criteria:
          measure: progress
          behavior: WeldingAgent
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 0.2
        value: 9.0
      - name: Dist10
        value: 10.0
